### ISSUE TITLE
OWL Concept For nominals

### ISSUE THREAD

**Issue by Demirrr** [dice-group/owlapy#1]
Would be great @alkidbaci if you could also implement a class for nominals in owlapy?

Ideally we should be able to compte and or operation between instances of this nominal class, e.g. {alice} and {bob} are two instances of Nominal class.
We can compute intersections and conjunctions between them
as well as \forall hasChild ({alice} and {bob})

If something is unclear with the description, please lemme know :)

See 4.3 Nominals of [DL](https://www.cs.ox.ac.uk/people/ian.horrocks/Publications/download/2014/KrSH14.pdf) if you need little but info about nominals

**Comment by alkidbaci** [comment]
May it be that `OWLObjectOneOf` is what you are looking for? Because in OWL, nominals are represented using the `owl:oneOf` construct and in owlapy we have the class [`OWLObjectOneOf`](https://github.com/dice-group/owlapy/blob/675816592f5ac27d8c0e254105c8e8d0d147c730/owlapy/model/__init__.py#L868) for instances. The intersection, conjunction and \forall can be achieved using [`OWLObjectIntersectionOf`](https://github.com/dice-group/owlapy/blob/675816592f5ac27d8c0e254105c8e8d0d147c730/owlapy/model/__init__.py#L650), [`OWLObjectUnionOf`](https://github.com/dice-group/owlapy/blob/675816592f5ac27d8c0e254105c8e8d0d147c730/owlapy/model/__init__.py#L642C15-L642C15), [`OWLObjectAllValuesFrom`](https://github.com/dice-group/owlapy/blob/675816592f5ac27d8c0e254105c8e8d0d147c730/owlapy/model/__init__.py#L588C11-L588C11).

**Comment by Demirrr** [comment]
Great! Then could you please close this issue after giving some examples of using owlapy README.md?

**Comment by alkidbaci** [comment]
Done!
