### ISSUE TITLE
Refactoring suggestions

### ISSUE THREAD

**Issue by alkidbaci** [dice-group/owlapy#11]
Counter-intuitive issues with the current structure:
1.  All owl objects are located in [owlapy/model/__init__.py](https://github.com/dice-group/owlapy/blob/develop/owlapy/model/__init__.py).
2.  Conversion methods are scattered in 3 files `render.py`, `parser.py` and `owl2sparql/converter.py`.

Proposed solution:
1. Group owl objects by semantic meaning in different modules. Import all in `owlapy/__init__.py`
2. Relocate `converter.py` in the owlapy directory, import conversion methods in `owlapy/__init__.py`.

**Comment by Demirrr** [comment]
The first phase of the refactoring is done with #21. Please continue on the second phase defined by the following todos

- [ ] Instead of using `from owlapy.model import ...` we use explicit imports, e.g. `from owlapy.owl_class_expression import ..`
- [ ]  Move the reamining class definitions (e.g. `OWLOntologyID`, .., `OWLReasoner` into a suitably named python script under owlapy
- [ ]  Continue refactoring until owlapy/model can be removed.

In the third phase, we will create modules under owlapy to group individual scripts
