### ISSUE TITLE
Fill up the documentation

### ISSUE THREAD

**Issue by alkidbaci** [dice-group/owlapy#12]
Add guides/description in [owlapy documentation](https://dice-group.github.io/owlapy/index.html).

**Comment by Demirrr** [comment]
It would be also great. If we could integrate https://www.w3.org/TR/owl2-syntax into almost in every class docstrings.

For instance, instead of  writing `An OWL 2 Class Expression` in the docstring, adding the respective link
of https://www.w3.org/TR/owl2-syntax/#Class_Expressions as well  would be helpful.

By this, we should be able to rethink our design decisions. 
For instance, it is not clear to me why OWLClassExpression should inherent from OWLPropertyRange
https://github.com/dice-group/owlapy/blob/459d337115988cddf716f3617d8c94721bbb119a/owlapy/model/__init__.py#L58
