### ISSUE TITLE
Missing dependency for Pellet reasoner?

### ISSUE THREAD

**Issue by LckyLke** [dice-group/owlapy#120]
```py
reasoner = SyncReasoner("KGs/Suramin/suramin.owl", "Pellet") 
```
Trying to load this reasoner throws an error:

`java.lang.java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter`

Adding the following dependency resolves this issue:
`https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api/2.2.3`

Java version:
`openjdk version "23" 2024-09-17`

**Comment by alkidbaci** [comment]
Yes sometimes specific reasoner and/or dataset require some specific dependency and we have to add them to `owlapy/jar_dependencies`. As you already mentioned, adding jaxb-api will fix the issue.
But I will say please add version [2.3.1](https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api/2.3.1) because it is closer to the release date of owlapi version we use (which means more compatibility and less possible errors). 
Considering this issue closed.

**Comment by LckyLke** [comment]
Ok I will add it 👍🏻
