### ISSUE TITLE
Using inheritance

### ISSUE THREAD

**Issue by Demirrr** [dice-group/owlapy#15]
1. We should use  [super()](https://docs.python.org/3/library/functions.html#super) to access inherited methods/attributes.
Currently, we do not use `super()` in all classes and I do not know what is the benefits of not using it.
2. We may want to use [propery()](https://docs.python.org/3/library/functions.html#property) as a decorator to access an attribute instead of a `get_` style function call.
3. `def __init__(self, iri: Union[IRI, str])`: should be located as the first function at each class

These suggestion hold for this class and many others defined therein.
https://github.com/dice-group/owlapy/blob/459d337115988cddf716f3617d8c94721bbb119a/owlapy/model/__init__.py#L381

**Comment by alkidbaci** [comment]
For point 1, from what I can see in the code there are places where `super()` is already used.  For the other part where `super()` is not used  there is no need to because there is no overwrite taking place. I moved common code of some classes to their superclass to reduce repetition wherever I saw fit (including the up mentioned `OWLObjectProperty`). The current architecture is pretty solid.

**Comment by Demirrr** [comment]
Very good. Thank you for the information
