### ISSUE TITLE
Convering OWL Class Expressions into sentences

### ISSUE THREAD

**Issue by Demirrr** [dice-group/owlapy#55]
**Feature: Convering OWL Class Expressions into Sentences**

Converting an OWL class expression into natural language sentences would be quite helpful.

**KG:**

```
<https://www.gennarovessio.com/artgraph-resources#67132>
    a artgraph:Artwork ;
    artgraph:about <https://www.gennarovessio.com/artgraph-resources#2888>, <https://www.gennarovessio.com/artgraph-resources#2943>, <https://www.gennarovessio.com/artgraph-resources#3053>, <https://www.gennarovessio.com/artgraph-resources#3085>, <https://www.gennarovessio.com/artgraph-resources#3577>, <https://www.gennarovessio.com/artgraph-resources#3823>, `<https://www.gennarovessio.com/artgraph-resources#3995>` ;
    artgraph:createdBy <https://www.gennarovessio.com/artgraph-resources#1258> ;
    artgraph:hasGenre <https://www.gennarovessio.com/artgraph-resources#17> ;
    artgraph:hasStyle <https://www.gennarovessio.com/artgraph-resources#40> ;
    artgraph:image_url "https://uploads7.wikiart.org/images/cornelis-springer/cityhall-paderborn.jpg" ;
    artgraph:name "cornelis-springer_cityhall-paderborn.jpg" ;
    artgraph:title "Cityhall Paderborn" .
```

**owlapy:** 

`OWLDataSomeValuesFrom(property=OWLDataProperty(IRI('https://www.gennarovessio.com/artgraph-schema#','title')),filler=OWLDataOneOf((OWLLiteral(Cityhall Paderborn),)))`

**DL concept:** 

`∃ title.{Cityhall Paderborn}` represents DataSomeValuesFrom with DataOneOf filler containing an OWL Literal. This owl class expression is "looking good" since the syntatic representation of the class expression reflects the semantic information.
Yet, `∃ hasGenre.{17}` doesn't look "good". 
It would be great to replace `17` with something useful about `https://www.gennarovessio.com/artgraph-resources#17`.

Ofcs, something being useful cannot be globally defined and depends on the usecases. 
For the time being I am thinking of replacing the URI with the object given a particular predicate.
For instance we can implement a function that takes a subject/head entity and a predicate/relation and returns a particular object, e.g., `label_info=function(subject="https://www.gennarovessio.com/artgraph-resources#17",predicate="http://www.w3.org/2000/01/rdf-schema#label")`

Ofcs, function can be implemented via a SPARQL query or a symbolic reasoner, or a linear search over knowledge base.
We can use this `label_info` to replace the `17`. We can very well apply this idea of replacement for the predicate `title`.

Such verbalized owl class expression can be given to an LLM to generate natural language questions in different languages.
Such feature would be very usefull in different applications.

What do you think about this feature ? @alkidbaci Do you have any suggestion for the implementation?

**Comment by alkidbaci** [comment]
If I got this right, we should not change the triples in the KB but just process it when we want to verbalize a CE.
Also I'm suggesting that you made an error when saying  `∃ title.{17}` and wanted to say `∃ hasGenre.{17}` instead.

The part that its making this difficult is how can we detect such individuals in a complex class expression, because 
the user isn't supposed to know the exact CE in advance, he just passes it to the verbalizer (maybe together with some 'label' property which we will use behind the scene) and expects the CE in natural language in return. Not only that but even if we extract these individuals from the CE in owlapy we cannot replace them with their 'label' because we have to do with object properties whose value should be an individual. We can construct some fake data properties that have the same IRI as the object properties and attach the 'label' value but that doesn't feel right. Therefore it seems like the replacement should take place in the DL expression because its a string.

So what I'm thinking may not be the best solution but it works like this:
We transform the CE to DL, and this function we build will first get the IRI's reminder of every object property in signature. 
Considering that we are aware that the the KB contains such individuals (that identified by some kind of id) we search in the DL expression for occurrence of the reminders we got earlier and retrieve the individual belonging to that object property since we know what to expect in DL syntax. Knowing the individual id and the ontology's IRI we can now construct an instance of this individual in owlapy. Then we can search for the 'label' (using a 'label property')  of this individual and replace it on the DL expression. The 'label' property needs to be predefined because its KB-specific buuut we can do something bold here that removes this requirement and makes it KB-independent:
Get every data property of the given individual and ask an LLM to find the property that best describes the individual (we can keep adjusting the prompt to get the best results) and tell the LLM to return only the value of that property and nothing else. We than use this value directly to replace the individual id in the DL. The final DL expression is then passed to the LLM again to verbalize it on natural language.

Example:
Lets say have this CE: `∃ hasGenre.{17}`. We get the IRI's reminder of object properties in signature which will contain
`hasGenre` and search for this in in the string  `∃ hasGenre.{17}`. Knowing that in DL syntax after the object property we have `.{` then we get the content inside `.{` and `}` and call this function recursively because it may contain another class expression inside. When we identify something as an individual reference, we construct the full IRI of it. In the example we detect `17`, attach `https://www.gennarovessio.com/artgraph-resources#` before it, construct the named individual in owlapy syntax and search for values of predicate `"https://www.gennarovessio.com/artgraph-resources#some_label"` which is predefined or we leave it to the LLM to find it as I described.

I'm not 100% confident about this approach, because there may be things that can go wrong obviously and maybe its not really straight forward to generalize this replacement process in the DL expression. For example i thought of a scenario when we have something like this `∃ hasSomeObject.{hasSomeData("some_string_data"}`. There is an object property in this case indeed, but no specific individual. However for this cases we can make it that it also search for occurrence of data properties and skips them until the end of the bracket. For this specific example the replacement function would and should do nothing. So the thing is there may be such specific scenarios for which we should create a generalized replacement process.

This idea got to me on first thought.  Maybe I will come up with something better in the meantime.

**Comment by Demirrr** [comment]
> If I got this right, we should not change the triples in the KB but just process it when we want to verbalize a CE.
> Also I'm suggesting that you made an error when saying ∃ title.{17} and wanted to say ∃ hasGenre.{17} instead.

Yes you are right :)

**Comment by Demirrr** [comment]
I have been thinking of implementing a function like [_simple_short_form_provider](https://github.com/dice-group/owlapy/blob/085bfb72aed10d5a6d92589149688d495bab203f/owlapy/render.py#L50C5-L50C32) and  a class like [DLSyntaxObjectRenderer](https://github.com/dice-group/owlapy/blob/085bfb72aed10d5a6d92589149688d495bab203f/owlapy/render.py#L60).
This new function takes an `x` OWL Entity as `_simple_short_form_provider` does but also takes a `dp` dataproperty (e.g. rdfs:label) and returns `o` such that `(x, dp, o)` exists. 

I guess something shown below would be easier to implement.


```python

def sentence_gen(e: OWLEntity) -> str:
    iri: IRI = e.iri
    # Let asssume that e corresponds to Einstein
    # Concat the all possibles return o 
    concatted_o = select ?o where { <http://dbpedia.org/resource/Albert_Einstein> <http://www.w3.org/2000/01/rdf-schema#label> ?o}
   # ...
   return post_processed_concatted_o

def owl_expression_to_sentences(o: OWLObject) -> str:
    return DLSyntaxObjectRenderer(short_form_provider=sentence_gen).render(o)
```

**Comment by alkidbaci** [comment]
The implementation is done: 
added [translating_short_form_provider](https://github.com/dice-group/owlapy/blob/376fb684c09844e6f56ae604fcd08cb2709f54a2/owlapy/render.py#L68) (explanation comments given in the code)

To initialize a `DLSyntaxObjectRenderer` using this short form provider:

```python
from functools import partial
from owlapy.render import DLSyntaxObjectRenderer, translating_short_form_provider

manager = OntologyManager()
onto = manager.load_ontology(IRI.create(f'file://../KGs/Test/test_ontology.owl'))
reasoner = OntologyReasoner(onto)

partial_provider = partial(translating_short_form_provider, reasoner=reasoner, rules=None)
a = DLSyntaxObjectRenderer(short_form_provider=partial_provider)
```
In this example i have used it with a owlapy reasoner. the `reasoner` argument can also be a triplestore (the algo expect to call the `query` method on this reasoner: `reasoner.query(sparql_query)`. 
I have not tried it on triplestore though but it works on owlapy reasoner.

**Comment by Demirrr** [comment]
I don't think that it is fully working right ?
```python
manager = OntologyManager()
onto = manager.load_ontology(IRI.create(
    f'dummy.nt'))
"""
<https://www.gennarovessio.com/artgraph-schema#Genre> a owl:Class;
  rdfs:label "Genree" .
"""
reasoner = OntologyReasoner(onto)

rules = {"https://www.gennarovessio.com/artgraph-schema#Genre": "http://www.w3.org/2000/01/rdf-schema#label"}
partial_provider = partial(translating_short_form_provider, reasoner=reasoner, rules=rules)
renderer = DLSyntaxObjectRenderer(short_form_provider=partial_provider)
x = OWLClass(IRI('https://www.gennarovessio.com/artgraph-schema#', 'Genre'))
print(renderer.render(x)) # still shows Genre
```

**Comment by alkidbaci** [comment]
Seems like my attempt to make this quick made me overlook something so obvious. As you have already noticed, when looking for `data_property_values` we should not look only for OWLNamedIndividual. 
Currently that method expects only OWLNamedIndividual but in reality, properties can also have a label. So I should probably update `data_property_values`  method to accept other OWLEntities as well.

**Comment by Demirrr** [comment]
No worries. I will take care of the part, where reasoner is not an OWLReasoner :)

**Comment by alkidbaci** [comment]
Just updated the code in accordance to what we mentioned earlier. Now it should be working fine for the OWLReasoner part.
Example i tried after adding `<rdfs:label>The awesome class</rdfs:label>`  to class `H` in `KGs/Test/test_ontology.owl`:

```python
from functools import partial
from owlapy.iri import IRI
from owlapy.owl_ontology_manager import OntologyManager
from owlapy.class_expression import OWLClass
from owlapy.owl_reasoner import OntologyReasoner
from owlapy.render import DLSyntaxObjectRenderer, translating_short_form_provider
manager = OntologyManager()
onto = manager.load_ontology(IRI.create(f'file://../KGs/Test/test_ontology.owl'))
reasoner = OntologyReasoner(onto)

partial_provider = partial(translating_short_form_provider, reasoner=reasoner, rules=None)
a = DLSyntaxObjectRenderer(short_form_provider=partial_provider)
ce = OWLClass("http://www.semanticweb.org/stefan/ontologies/2023/1/untitled-ontology-11#H")
print(a.render(ce)) # prints "The awesome class"
```

**Comment by Demirrr** [comment]
Thank you! Please proceed with the next release :)
