### ISSUE TITLE
Using Abstract in the name of abstract classes

### ISSUE THREAD

**Issue by Demirrr** [dice-group/owlapy#67]
Although OWLOntology is an abstract class, its name syntacticaly does not carry this information. Perhaps, we can use 
`BaseOWLOntology` or `AbstractOWLOntology`.

**Comment by alkidbaci** [comment]
If we do this maybe it would be better if we update the naming of the implementation classes as well. For example:
- `Ontology` ==> `OWLOntology`
- `OntologyManager` ==> `OWLOntologyManager`
- ...

This may introduce some confusion since they will be renamed to what is currently an abstract class but I think its for the best since other owl related classes (ex. `OWLObjectProperty`, `OWLClass`, etc) have the 'OWL' part in their naming. So basically we set the same standard for all implementing classes. What do you think?

**Comment by alkidbaci** [comment]
Or maybe thats not the best thing to do, since we can have different implementation for those abstract classes and would be better to find a more fitting name to each implementing class. Previously they had the "owlready2" part in their name indicating that they are using that library. Now that i give a second thought, we should probably just leave them like they are for the moment.

**Comment by Demirrr** [comment]
Thank you for sharing your reasoning :)

I think that the both suggestions are good and we should implement them. Yet, for the time being, I would suggest to focus on the former, namely, OWLOntololgy abstract class should be named as `BaseOWLOntology` or `AbstractOWLOntology`.
