### ISSUE TITLE
Reducing the number of jar files

### ISSUE THREAD

**Issue by Demirrr** [dice-group/owlapy#74]
Do we need all these jar files for https://github.com/dice-group/owlapy/tree/develop/owlapy/jar_dependencies ?

**Comment by alkidbaci** [comment]
I am afraid they are all necessary because I remember adding them one by one (with some exceptions) when trying to make the java code work. Some of them are needed for specific functionalities like `jgrapht-core-1.2.0.jar` for example is needed for some of the methods of pellet reasoner. However I can still double check to make sure there isn't any unnecessary library.

**Comment by Demirrr** [comment]
Thank you. It would be great to double check it
