### ISSUE TITLE
Remove Caching

### ISSUE THREAD

**Issue by Demirrr** [dice-group/owlapy#97]
We should not add any functionalities that cannot be disabled by the user. StructuralReasoner must be refactored!

**Comment by alkidbaci** [comment]
Caching can be disabled or enabled by the user. If you are referring to the automatic disable of caching when ontology modification is detected then that's something that is done to protect the user without him having to do the job manually because if axioms are added or removed from the ontology where the reason methods are called then in order to avoid inconsistencies with the information stored in cache we need to disable it.

**Comment by Demirrr** [comment]
> Caching can be disabled or enabled by the user

These lines show that we cannot disable right ?!
https://github.com/dice-group/owlapy/blob/56888c712eff55987d2523a0457ffc4a81a377a8/owlapy/owl_reasoner.py#L92C1-L111C15

**Comment by alkidbaci** [comment]
Okay there seems to be a misunderstanding, I thought we were talking about class and property cache. Its true that the LRU caches cannot be disabled, but since they are now gone #100 there is no cache left that cant be disabled.
